### ISSUE TITLE
Refactor DateTime class

### ISSUE THREAD

**Issue by anosach-luxoft** [LuxoftSDL/sdl_core_winport#110]
- Remove class `DateTime` and declare all functions just in `date_time` namespace
- Rework `getCurrentTime()` function in Qt version because it works incorrectly
- `timeval` struct uses in Qt version is not crossplatform
- Analyze all related functions for useless and redundant

**Comment by malirod** [comment]
`getCurrentTime` already fixed for Qt

**Comment by anosach-luxoft** [comment]
An appropriate issue has been created in [JIRA](https://adc.luxoft.com/jira/browse/SDLWIN-351)
