### ISSUE TITLE
Create script which will prepare the release builds

### ISSUE THREAD

**Issue by malirod** [LuxoftSDL/sdl_core_winport#115]
Currently we create release builds manually. It's easy to forget to update files (Policy.dll) or some other file. It would be nice to have a script (cmd or python) in infrastructure which will build and copy output files to some place. This will allow to reduce the possibility to include into release wrong files.

**Comment by pestOO** [comment]
Just a note: Please, use `python` in all cases where it can replace system-specific scripts

**Comment by malirod** [comment]
In the context of the win porting this is issue will not be addressed.
