### ISSUE TITLE
Rework `IsCertificateUpdateRequired` method

### ISSUE THREAD

**Issue by AGaliuzov** [LuxoftSDL/sdl_core_winport#130]
`IsCertificateUpdateRequired` method should be called during starting of new session with mobile device. This method uses the due date of certificate. In case SDL doesn't have certficate at all there is nothing to check and method all the time returns true since the variable which we use to store certificate time contains default value (01/01/1900).

To avoid such problem SDL uses `certificate_exists_` flag in order to understand if certificate has been set to the SSL context. Using this flag currently workable but error prone solution. So we need to figure out how to implement proper check for certificate date.

**Comment by malirod** [comment]
`CryptoManagerImpl::set_certificate` should be refactored. The first half of the method which doesn't change the invariant of the CryptoManagerImpl should be extracted.

starting from the `SSL_CTX_use_certificate` call the CryptoManagerImpl invariant changes. This should be handled correctly.
Currently it's possible that during first call of the set_certificate the certificate_exists_  wil lbe set to true. But on the second call, during the SSL_CTX_use_certificate call or after we will exit the method. and the flag will be still true. There is no reset before the calls which can change the invariant.

Also it's clear is what is going on with the CryptoManagerImpl  invariant after the failed call of the SSL_CTX_check_private_key. Possibly the CryptoManagerImpl   becomes invalid, thus there should be some additional handling. Possibly just write to the log and exit is not enough.

**Comment by malirod** [comment]
Resolved with #131
