### ISSUE TITLE
Change the interface of the Pipe::Send and Socket::Send

### ISSUE THREAD

**Issue by malirod** [LuxoftSDL/sdl_core_winport#136]
Return just int32_t instead of bool result + out param. E.g. on windows platform the result is int. This allows to return -1 as error flag. The original problem was that send on posix returns ssize_t.
On my opinion int32_t is more that enough to store the bytes sent. typical tcp frame buffer is 4096 bytes. Input and output queues also have sizes which fits into the int. If we will try more than available free space in the buffer we would get ewouldblock error.

Change in the interface will make the usage much more clear.

**Comment by anosach-luxoft** [comment]
An appropriate issue has been created in [JIRA](https://adc.luxoft.com/jira/browse/SDLWIN-350)
