### ISSUE TITLE
QSqlQuery warnings in log

### ISSUE THREAD

**Issue by anosach-luxoft** [LuxoftSDL/sdl_core_winport#137]
A lot of Qt warnings present in log:
`QSqlQuery::value: not positioned on a valid record`
See attached log file
[SmartDeviceLink.txt](https://github.com/LuxoftSDL/sdl_core_winport/files/121475/SmartDeviceLink.txt)

**Comment by malirod** [comment]
Related [JIRA](https://adc.luxoft.com/jira/browse/SDLWIN-356) ticket
