### ISSUE TITLE
There are a lot of warnings regarding missing pdb files for the openssl libs. We can ingore this.

### ISSUE THREAD

**Issue by malirod** [LuxoftSDL/sdl_core_winport#91]
We are not going to debug openssl. thus we can ignore these warnings. this will make build output more clean.

**Comment by nk0leg** [comment]
#129 fixed of problem for windows native version.
For fix the Qt-version you need rebuild `libeay32.lib` and `ssleay32.lib` with another flags.

For this purpose:
1. Download and install latest stable `nasm`. On current moment it's [2.11.08](http://www.nasm.us/pub/nasm/releasebuilds/2.11.08/)
2. modify ms\openssl_setup.cmd:
   -  in line 24 -  remove `no-asm`
   -  in line 39 - replace `ms\do_ms` on `ms\do_nasm`
3. remove build\openssl_win_x86 folder
4. relaunch `setup_Qt_x86.cmd`

**Comment by malirod** [comment]
Installation of the nasm makes env setup more complex. So lets forget about openssl warnings under Qt.
